name: Memory Leak Check

on: push

jobs:
  heapcheck-solve:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Install gproftools
        run: |
          sudo apt-get install -y google-perftools libgoogle-perftools-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libtcmalloc.so /usr/lib/libtcmalloc.so

      - name: Build
        run: make gperftools

      - name: Detect Leaks
        run: ./raytracer
        env:
          HEAPCHECK: normal
