name: Memory Leak Check

on: push

jobs:
  heapcheck-solve:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive

      - name: Install project deps
        run: |
          sudo apt-get update
          sudo apt-get -y -qq install libxrandr-dev mesa-common-dev libgl-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Build project deps deps
        run: |
          cd deps/glfw/
          mkdir build
          cd build
          cmake .. -DBUILD_SHARED_LIBS=ON
          make
          cd ../../

          cd cJSON
          mkdir build
          cd build
          cmake ..
          make
          cd ../../
        env:
          MAKEFLAGS: -j3

      - name: Install gproftools
        run: |
          sudo apt-get install -y google-perftools libgoogle-perftools-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libtcmalloc.so /usr/lib/libtcmalloc.so

      - name: Build
        run: make gperftools

      - name: Detect Leaks
        run: make run
        env:
          HEAPCHECK: normal
