name: Benchmarks Test

on: push

jobs:
  run-benchmarks:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-10.15]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Build
        run: make

      - name: Run
        run: ./raytracer
